/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 TheTARDISfinal.gltf --transform --simplify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TheTARDISfinal-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tardis.geometry} material={materials['blue paintwork']} position={[0, 3.59, 0]}>
        <mesh geometry={nodes.bottom_hinge.geometry} material={materials.gold} position={[-1.11, 0.16, 1.67]} scale={[0.56, 1, 0.56]} />
        <mesh geometry={nodes.top_hinge.geometry} material={materials.gold} position={[-1.11, 0.75, 1.67]} scale={[0.56, 1, 0.56]} />
        <mesh geometry={nodes.Cylinder.geometry} material={materials.gold} position={[0.21, 0.6, 1.6]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.door_handle.geometry} material={materials.lead} position={[0.21, 0.14, 1.75]} scale={0.83} />
        <mesh geometry={nodes.panelhandle.geometry} material={materials.lead} position={[-0.37, 0.47, 1.71]} scale={0.46} />
        <mesh geometry={nodes.Frontpanel.geometry} material={materials.frontpanel} position={[-0.72, 0.45, 1.63]} scale={[0.36, 0.45, 0.04]} />
        <mesh geometry={nodes.interiorlamp.geometry} material={materials.brightlight} position={[0, 2.94, 0]} rotation={[1.47, -0.01, 0]} />
        <mesh geometry={nodes.toplamp.geometry} material={materials.brightlight} position={[0, 4.37, 0]} rotation={[1.47, -0.01, 0]} />
        <mesh geometry={nodes.lamphousing.geometry} material={materials.flatglass} position={[0, 4.37, 0]} scale={[1.11, 1.08, 1.11]} />
        <mesh geometry={nodes.sign.geometry} material={materials.flatglass} />
        <mesh geometry={nodes.sign001.geometry} material={materials.flatglass} />
        <mesh geometry={nodes.windows.geometry} material={materials.flatglass} />
      </mesh>
      <mesh geometry={nodes.lighting2.geometry} material={materials.brightlight} position={[-8.78, 2.78, -22.07]} rotation={[1.54, 0.23, -1.71]} />
      <mesh geometry={nodes.lighting1.geometry} material={materials.brightlight} position={[3.91, 7.36, 16.81]} rotation={[1.2, 0.16, -0.9]} />
    </group>
  )
}

useGLTF.preload('/TheTARDISfinal-transformed.glb')
