/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/TARDIS.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube001.geometry}
        material={materials["Material.002"]}
        position={[0, 2.7, 0]}
      />
      <group position={[0, 0.05, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base_1.geometry}
          material={materials["Blue Painted Wood Base"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base_2.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pillar_Tops.geometry}
          material={materials["Blue Painted Wood Pillar Tops"]}
          position={[-0.57, 2.35, 0.57]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window_Frame.geometry}
          material={materials["White Painted Wood Widows"]}
          position={[0.53, 1.51, 0.24]}
          rotation={[0, Math.PI / 2, 0]}
        >
          <group
            position={[0, 0.21, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.49, 1, 0.57]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Window_Glass_1.geometry}
              material={materials["Obscured Glass"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Window_Glass_2.geometry}
              material={materials["Procedural Frosted Glass"]}
            />
          </group>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window_Frame003.geometry}
          material={materials["White Painted Wood Widows"]}
          position={[0.53, 1.51, -0.24]}
          rotation={[0, Math.PI / 2, 0]}
        >
          <group
            position={[0, 0.21, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.49, 1, 0.57]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Window_Glass003_1.geometry}
              material={materials["Obscured Glass"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Window_Glass003_2.geometry}
              material={materials["Procedural Frosted Glass"]}
            />
          </group>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window_Frame004.geometry}
          material={materials["White Painted Wood Widows"]}
          position={[0.24, 1.51, -0.53]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <group
            position={[0, 0.21, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.49, 1, 0.57]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Window_Glass004_1.geometry}
              material={materials["Obscured Glass"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Window_Glass004_2.geometry}
              material={materials["Procedural Frosted Glass"]}
            />
          </group>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window_Frame005.geometry}
          material={materials["White Painted Wood Widows"]}
          position={[-0.24, 1.51, -0.53]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <group
            position={[0, 0.21, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.49, 1, 0.57]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Window_Glass005_1.geometry}
              material={materials["Obscured Glass"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Window_Glass005_2.geometry}
              material={materials["Procedural Frosted Glass"]}
            />
          </group>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window_Frame006.geometry}
          material={materials["White Painted Wood Widows"]}
          position={[-0.53, 1.51, -0.24]}
          rotation={[0, -1.57, 0]}
        >
          <group
            position={[0, 0.21, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.49, 1, 0.57]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Window_Glass006_1.geometry}
              material={materials["Obscured Glass"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Window_Glass006_2.geometry}
              material={materials["Procedural Frosted Glass"]}
            />
          </group>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window_Frame007.geometry}
          material={materials["White Painted Wood Widows"]}
          position={[-0.53, 1.51, 0.24]}
          rotation={[0, -1.57, 0]}
        >
          <group
            position={[0, 0.21, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.49, 1, 0.57]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Window_Glass007_1.geometry}
              material={materials["Obscured Glass"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Window_Glass007_2.geometry}
              material={materials["Procedural Frosted Glass"]}
            />
          </group>
        </mesh>
        <group position={[-0.46, 1, 0.53]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ceiling_1.geometry}
            material={materials["Blue Painted Wood Ceiling"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ceiling_2.geometry}
            material={materials["White Painted Wood Ceiling"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Signs_1.geometry}
            material={materials["Blue Painted Wood Sign"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Signs_2.geometry}
            material={materials["White Painted Wood Sign"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Signs_3.geometry}
            material={materials["Glass Sign"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Door_Top_Trim.geometry}
            material={materials["Blue Painted Wood Door Top Trim"]}
          />
        </group>
        <group position={[-0.48, 1, 0.53]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Door_Left_1.geometry}
            material={materials["Blue Painted Wood Door Left"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Door_Left_2.geometry}
            material={materials["White Painted Wood Door Left"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Window_Frame001.geometry}
            material={materials["White Painted Wood Widows"]}
            position={[0.22, 0.51, 0]}
          >
            <group
              position={[0, 0.21, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.49, 1, 0.57]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Window_Glass001_1.geometry}
                material={materials["Obscured Glass"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Window_Glass001_2.geometry}
                material={materials["Procedural Frosted Glass"]}
              />
            </group>
          </mesh>
          <group
            position={[0.41, 0, 0.04]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Yale_Lock_1.geometry}
              material={materials["Lock Brass Light"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Yale_Lock_2.geometry}
              material={materials["Lock Brass Dark"]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pull_to_Open_Panel_1.geometry}
            material={materials["Blue Painted Wood Pull To Open Sign"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pull_to_Open_Panel_2.geometry}
            material={materials["Pull to Open sign"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roof.geometry}
          material={materials["Blue Painted Wood Roof"]}
          position={[0, 2.39, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lamp_Base.geometry}
            material={materials["Blue Painted Wood Lamp Base"]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Lamp_Bottom.geometry}
              material={materials["Blue Painted Wood Lamp Bottom"]}
              position={[0, 0.12, 0]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Lamp_Lens.geometry}
                material={materials["Lamp Glass"]}
                position={[0, 0.08, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Lamp_Struts.geometry}
                material={materials["Blue Painted Wood Lamp Struts"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Lamp_Top.geometry}
                material={materials["Blue Painted Wood Lamp Top"]}
                position={[0, 0.14, 0]}
              />
            </mesh>
          </mesh>
        </mesh>
        <group position={[0.46, 1, 0.53]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Door_Right_1.geometry}
            material={materials["Blue Painted Wood Door Right"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Door_Right_2.geometry}
            material={materials["White Painted Wood Door Right"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Window_Frame002.geometry}
            material={materials["White Painted Wood Widows"]}
            position={[-0.22, 0.51, 0]}
          >
            <group
              position={[0, 0.21, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.49, 1, 0.57]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Window_Glass002_1.geometry}
                material={materials["Obscured Glass"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Window_Glass002_2.geometry}
                material={materials["Procedural Frosted Glass"]}
              />
            </group>
          </mesh>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pillars.geometry}
          material={materials["Blue Painted Wood Pillars"]}
          position={[-0.56, 0, 0.56]}
          rotation={[0, 1.57, 0]}
        />
        <group position={[0.53, 1, -0.46]} rotation={[0, 1.57, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Walls_1.geometry}
            material={materials["Blue Painted Wood Walls"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Walls_2.geometry}
            material={materials["White Painted Wood Walls"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wall_Trim.geometry}
            material={materials["Blue Painted Wood Wall Trim"]}
            position={[-0.46, -1, 0.04]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/TARDIS.glb");