on:
  push:
    branches:
      - 'test'
permissions:
  contents: read
  pages: write
  id-token: write 
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.1.1
      with:
        path: build
